### ISSUE TITLE
add new structure elements

### ISSUE THREAD

**Issue by Michaelfengshi** [simonp0420/PSSFSS.jl#41]
Can you add the FSS structure in the figure?  and Can this complex FSS structure be simulated by PSSFSS?

**Comment by simonp0420** [comment]
I've been considering adding some type of chiral element like your FSS II and FSS III for some time, and this will be quite easy using the new structured mesher.  Actually, these look like the same topology to me, just different choices of geometrical parameters.  Is there any difference between them that I'm missing? 

FSS I (shown in (a) of your figure) will be a bit more difficult, but doable.  I don't see the purpose of the decorations in the corners of this element.  Are they truly functional?  I would think they would resonate at a much higher frequency than the main  sinuous structure in the middle.

I'll see if I can get the II/III element implemented in the next few days.

Can you send me a reference where these elements are used?

**Comment by simonp0420** [comment]
I forgot to mention that eventually, I would like for the user to be able to specify an arbitrary geometry in terms of polygon vertex coordinates.

**Comment by Michaelfengshi** [comment]
Hi, Dr. Simon
Thanks for your thoughtful consideration and your kindly help. 
You're Right. The purpose of the decorations in the corners of the FSS I is that they can increase their resonant frequency in the high frequency band.

Sincerely,
Feng Shi

**Comment by simonp0420** [comment]
I released PSSFSS version 1.4.1 today. It now includes the manji element, documented [here](https://simonp0420.github.io/PSSFSS.jl/stable/reference/#PSSFSS.Elements.manji), which allows you to model your second and third elements.  Also see examples in the updated element gallery [here](https://simonp0420.github.io/PSSFSS.jl/stable/PSS_&_FSS_Element_Gallery/#Manji).   Not sure when I'll have time to look at your sinuous cross element.

**Comment by Michaelfengshi** [comment]
Thank you for your prompt reply and hard work, I will start testing in the next few days. By the way, I would be grateful if you counld implement the sinuous cross element like FSS I at your convenience.

**Comment by simonp0420** [comment]
Question:  Are $l_1$, $l_2$, and $l_3$ in your diagram above supposed to be unit cell dimensions, or are these boundary square loops supposed to be smaller than the entire unit cell?

**Comment by Michaelfengshi** [comment]
These bounding square rings should be smaller than the entire cell.

**Comment by Michaelfengshi** [comment]
These boundary square loops are smaller than the entire cell.

**Comment by simonp0420** [comment]
👍 I will have the sinuous element completed in a couple of days, and I will modify the manji element to allow the boundary loop to be smaller than the unit cell.

**Comment by Michaelfengshi** [comment]
👍

**Comment by simonp0420** [comment]
I've got a preliminary implementation with any number of "arms" and any number of rings per arm.  Below is an example with 3 arms and 6 rings per arm:
![sinuous1](https://user-images.githubusercontent.com/4294361/226448546-74d5c0be-3875-450f-8cd8-e51988c4580d.svg)

~As you can see, I've implemented the "gap" between adjacent arms in terms of a wedge angle, so that the separation between arms varies with radial distance from the center of the structure.  I hope this will be acceptable.  Otherwise, I don't know how to define the orientation of the sides of the arms.~
Edit: I figured it out:

![temp](https://user-images.githubusercontent.com/4294361/226486779-1cb3631c-800e-4a55-95df-059ae564d321.svg)

**Comment by simonp0420** [comment]
I just tagged version 1.5 of PSSFSS that contains the `sinuous` element.  Both the `manji` and `sinuous` outer "rims" may be smaller than the unit cell.  @Michaelfengshi please try out the new elements and let me know if they are satisfactory.  If so, I will close this issue.

**Comment by Michaelfengshi** [comment]
Thanks, after generating a series of structures with these new elements and testing them, the elements are perfectly suited to our use, thank you again.

**Comment by simonp0420** [comment]
You're welcome!  I look forward to seeing the results of your research one of these days 😄

**Comment by Michaelfengshi** [comment]
------------------ Original ------------------From: Peter Simon  ***@***.***>Date: Wed,Mar 22,2023 10:19 PMTo: simonp0420/PSSFSS.jl ***@***.***>Cc: Michaelfengshi ***@***.***>, Mention ***@***.***>Subject: Re: [simonp0420/PSSFSS.jl] add new structure elements (Issue #41)
You're welcome!  I look forward to seeing the results of your research one of these days 😄

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/simonp0420/PSSFSS.jl/issues/41#issuecomment-1479650618",
"url": "https://github.com/simonp0420/PSSFSS.jl/issues/41#issuecomment-1479650618",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Michaelfengshi** [comment]
Okay, thank you again for everything you've done.------------------ Original ------------------From: Peter Simon  ***@***.***>Date: Wed,Mar 22,2023 10:19 PMTo: simonp0420/PSSFSS.jl ***@***.***>Cc: Michaelfengshi ***@***.***>, Mention ***@***.***>Subject: Re: [simonp0420/PSSFSS.jl] add new structure elements (Issue #41)
You're welcome!  I look forward to seeing the results of your research one of these days 😄

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/simonp0420/PSSFSS.jl/issues/41#issuecomment-1479650618",
"url": "https://github.com/simonp0420/PSSFSS.jl/issues/41#issuecomment-1479650618",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
